// Package migrationgen は dialect 共通のマイグレーションテンプレート
// (internal/db/migrations/src/*.sql.tmpl) から SQLite / PostgreSQL 用の
// goose マイグレーションファイルを生成する。
//
// 生成物はコミットされ、実行時には embed された生成物のみを使う。
// テンプレートと生成物の一致は internal/db のテストで検査する。
package migrationgen

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"
)

// Dialect 名 (出力ディレクトリ名と一致させる)。
const (
	SQLite   = "sqlite"
	Postgres = "postgres"
)

// Dialects は生成対象の dialect 一覧。
var Dialects = []string{SQLite, Postgres}

const (
	// SQLite のタイムスタンプ列に課す固定長 UTC 形式 (YYYY-MM-DDTHH:MM:SS.ffffffZ)。
	tsGlob = "[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z"
	// SQLite の日付列に課す形式 (YYYY-MM-DD)。
	dateGlob = "[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]"
)

type lateFK struct {
	table, column, ref string
}

// Render はテンプレート文字列を指定 dialect の SQL に展開し、Down セクションを付与して返す。
func Render(name, src, dialect string) (string, error) {
	if dialect != SQLite && dialect != Postgres {
		return "", fmt.Errorf("migrationgen: unknown dialect %q", dialect)
	}
	sqlite := dialect == SQLite
	var lates []lateFK

	funcs := template.FuncMap{
		"pk": func() string {
			if sqlite {
				return "id INTEGER PRIMARY KEY AUTOINCREMENT"
			}
			return "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
		},
		"ref": func() string {
			if sqlite {
				return "INTEGER"
			}
			return "BIGINT"
		},
		"real": func() string {
			if sqlite {
				return "REAL"
			}
			return "DOUBLE PRECISION"
		},
		"blob": func() string {
			if sqlite {
				return "BLOB"
			}
			return "BYTEA"
		},
		"T": func() string {
			if sqlite {
				return "1"
			}
			return "TRUE"
		},
		"F": func() string {
			if sqlite {
				return "0"
			}
			return "FALSE"
		},
		"bool": func(col string, def bool) string {
			if sqlite {
				d := "0"
				if def {
					d = "1"
				}
				return fmt.Sprintf("%s INTEGER NOT NULL DEFAULT %s CHECK (%s IN (0, 1))", col, d, col)
			}
			d := "FALSE"
			if def {
				d = "TRUE"
			}
			return fmt.Sprintf("%s BOOLEAN NOT NULL DEFAULT %s", col, d)
		},
		"ts": func(col string) string {
			if sqlite {
				return fmt.Sprintf("%s TEXT CHECK (%s GLOB '%s')", col, col, tsGlob)
			}
			return col + " TIMESTAMPTZ"
		},
		"date": func(col string) string {
			if sqlite {
				return fmt.Sprintf("%s TEXT CHECK (%s GLOB '%s')", col, col, dateGlob)
			}
			return col + " DATE"
		},
		"json": func(col string) string {
			if sqlite {
				return fmt.Sprintf("%s TEXT CHECK (json_valid(%s))", col, col)
			}
			// JSONB はキー順を保持しない (保存クエリのフィルタ順など Redmine は順序を表示に使う) ため JSON 型にする
			return col + " JSON"
		},
		"latefk": func(table, col, ref string) string {
			if sqlite {
				// SQLite は未作成テーブルへの REFERENCES を許すので列定義に埋め込む。
				return " REFERENCES " + ref
			}
			lates = append(lates, lateFK{table, col, ref})
			return ""
		},
		"latefks": func() string {
			if sqlite || len(lates) == 0 {
				return ""
			}
			var b strings.Builder
			b.WriteString("\n-- 前方参照の外部キー\n")
			for _, l := range lates {
				fmt.Fprintf(&b, "ALTER TABLE %s ADD CONSTRAINT %s_%s_fkey FOREIGN KEY (%s) REFERENCES %s;\n",
					l.table, l.table, l.column, l.column, l.ref)
			}
			return b.String()
		},
	}

	t, err := template.New(name).Funcs(funcs).Option("missingkey=error").Parse(src)
	if err != nil {
		return "", fmt.Errorf("migrationgen: parse %s: %w", name, err)
	}
	var buf bytes.Buffer
	data := map[string]bool{"SQLite": sqlite, "Postgres": !sqlite}
	if err := t.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("migrationgen: execute %s: %w", name, err)
	}
	up := strings.TrimRight(buf.String(), "\n") + "\n"
	return header(name) + up + "\n" + downSection(up, sqlite), nil
}

func header(name string) string {
	return "-- Code generated by internal/db/internal/migrationgen from migrations/src/" + name + ". DO NOT EDIT.\n\n"
}

var createTableRe = regexp.MustCompile(`(?m)^CREATE TABLE (\w+)`)

// downSection は Up 中の CREATE TABLE を逆順に DROP する Down セクションを作る。
func downSection(up string, sqlite bool) string {
	var b strings.Builder
	b.WriteString("-- +goose Down\n")
	if sqlite {
		// 相互参照するテーブルがあるため、外部キー検査をコミット時まで遅延させる。
		b.WriteString("PRAGMA defer_foreign_keys = ON;\n")
	}
	m := createTableRe.FindAllStringSubmatch(up, -1)
	for i := len(m) - 1; i >= 0; i-- {
		if sqlite {
			fmt.Fprintf(&b, "DROP TABLE IF EXISTS %s;\n", m[i][1])
		} else {
			fmt.Fprintf(&b, "DROP TABLE IF EXISTS %s CASCADE;\n", m[i][1])
		}
	}
	return b.String()
}

// OutputName はテンプレートファイル名から生成ファイル名を求める。
func OutputName(tmplName string) string {
	return strings.TrimSuffix(tmplName, ".tmpl")
}

// Generate は srcDir の *.sql.tmpl を全て展開し、outDir/<dialect>/ に書き出す。
func Generate(srcDir, outDir string) error {
	files, err := filepath.Glob(filepath.Join(srcDir, "*.sql.tmpl"))
	if err != nil {
		return err
	}
	if len(files) == 0 {
		return fmt.Errorf("migrationgen: no templates in %s", srcDir)
	}
	for _, f := range files {
		src, err := os.ReadFile(f)
		if err != nil {
			return err
		}
		name := filepath.Base(f)
		for _, d := range Dialects {
			out, err := Render(name, string(src), d)
			if err != nil {
				return err
			}
			dir := filepath.Join(outDir, d)
			if err := os.MkdirAll(dir, 0o755); err != nil {
				return err
			}
			if err := os.WriteFile(filepath.Join(dir, OutputName(name)), []byte(out), 0o644); err != nil {
				return err
			}
		}
	}
	return nil
}
