// SPDX-License-Identifier: BSD-3-Clause AND GPL-2.0-or-later
// Copyright (C) 2026 mikuta0407 and Buropher contributors
// Forked from golang.org/x/net/html v0.58.0 (Copyright 2009 The Go Authors,
// BSD-3-Clause; see LICENSE in this directory) and modified for Buropher.

// Code generated by "stringer -type NodeType"; DO NOT EDIT.

package h5

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorNode-0]
	_ = x[TextNode-1]
	_ = x[DocumentNode-2]
	_ = x[ElementNode-3]
	_ = x[CommentNode-4]
	_ = x[DoctypeNode-5]
	_ = x[RawNode-6]
	_ = x[scopeMarkerNode-7]
}

const _NodeType_name = "ErrorNodeTextNodeDocumentNodeElementNodeCommentNodeDoctypeNodeRawNodescopeMarkerNode"

var _NodeType_index = [...]uint8{0, 9, 17, 29, 40, 51, 62, 69, 84}

func (i NodeType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_NodeType_index)-1 {
		return "NodeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeType_name[_NodeType_index[idx]:_NodeType_index[idx+1]]
}
