# frozen_string_literal: true
#
# ActiveSupport::TimeZone の一覧（MAPPING と TimeZone.all の並び順・基準オフセット）から zones_gen.go を生成する。
# go generate ./internal/i18n で実行される（timezone.go の go:generate 行を参照）。
# 標準出力に Go ソースを書き出す。

zones = ActiveSupport::TimeZone.all
out = +''
out << "// Code generated by gen_timezones.rb from activesupport #{ActiveSupport.version} (tzinfo #{TZInfo::VERSION}); DO NOT EDIT.\n\n"
out << "package i18n\n\n"
out << "// timeZones は ActiveSupport::TimeZone.all と同じ順序（基準 UTC オフセット → 名前）の一覧。\n"
out << "// UTCOffset は生成時点の tzinfo の base_utc_offset（秒）。\n"
out << "var timeZones = []TimeZone{\n"
zones.each do |z|
  out << "\t{Name: #{z.name.dump}, Identifier: #{ActiveSupport::TimeZone::MAPPING[z.name].dump}, UTCOffset: #{z.utc_offset}},\n"
end
out << "}\n"
$stdout.write(out)
