# frozen_string_literal: true
#
# ActiveSupport::TimeZone の一覧（MAPPING と TimeZone.all の並び順・基準オフセット）から zones_gen.go を生成する。
# go generate ./internal/i18n で実行される（timezone.go の go:generate 行を参照）。
# 標準出力に Go ソースを書き出す。

# TimeZone#utc_offset は「現在時刻」の期間の base_utc_offset を返し、システムの zoneinfo を使う場合は
# 推定値が時期で変わる（Africa/Casablanca は 1 月に +01:00、ラマダン後の時期に +00:00 になる）。
# 生成結果を決定的にするため、互換テストの固定時刻（COMPAT_FROZEN_TIME、既定 2026-01-15 12:00:00 UTC）で評価し、
# ActiveSupport::TimeZone#<=> と同じ（オフセット → 名前）順に並べる。
at = Time.parse(ENV['COMPAT_FROZEN_TIME'].presence || '2026-01-15 12:00:00 UTC').utc
offset = ->(z) { z.tzinfo.period_for(at).base_utc_offset }
zones = ActiveSupport::TimeZone.all.sort_by { |z| [offset.(z), z.name] }
out = +''
out << "// SPDX-License-Identifier: GPL-2.0-or-later\n// Copyright (C) 2026 mikuta0407 and Buropher contributors\n\n// Code generated by gen_timezones.rb from activesupport #{ActiveSupport.version} (tzinfo #{TZInfo::VERSION}); DO NOT EDIT.\n\n"
out << "package i18n\n\n"
out << "// timeZones は ActiveSupport::TimeZone.all と同じ順序（基準 UTC オフセット → 名前）の一覧。\n"
out << "// UTCOffset は #{at.strftime('%Y-%m-%d %H:%M:%S UTC')} 時点の tzinfo の base_utc_offset（秒）。\n"
out << "var timeZones = []TimeZone{\n"
zones.each do |z|
  out << "\t{Name: #{z.name.dump}, Identifier: #{ActiveSupport::TimeZone::MAPPING[z.name].dump}, UTCOffset: #{offset.(z)}},\n"
end
out << "}\n"
$stdout.write(out)
