// SPDX-License-Identifier: GPL-2.0-or-later AND MIT
// Copyright (C) 2026 mikuta0407 and Buropher contributors
// Portions ported from libxml2 (https://gitlab.gnome.org/GNOME/libxml2),
// Copyright (C) 1998-2012 Daniel Veillard, MIT License.

// Code generated from libxml2 2.13.9 HTMLparser.c (html40EntitiesTable). DO NOT EDIT.

package htmldom

// html40Entities は libxml2 が認識する HTML 4 の名前付き文字参照。
var html40Entities = map[string]rune{
	"quot":     34,
	"amp":      38,
	"apos":     39,
	"lt":       60,
	"gt":       62,
	"nbsp":     160,
	"iexcl":    161,
	"cent":     162,
	"pound":    163,
	"curren":   164,
	"yen":      165,
	"brvbar":   166,
	"sect":     167,
	"uml":      168,
	"copy":     169,
	"ordf":     170,
	"laquo":    171,
	"not":      172,
	"shy":      173,
	"reg":      174,
	"macr":     175,
	"deg":      176,
	"plusmn":   177,
	"sup2":     178,
	"sup3":     179,
	"acute":    180,
	"micro":    181,
	"para":     182,
	"middot":   183,
	"cedil":    184,
	"sup1":     185,
	"ordm":     186,
	"raquo":    187,
	"frac14":   188,
	"frac12":   189,
	"frac34":   190,
	"iquest":   191,
	"Agrave":   192,
	"Aacute":   193,
	"Acirc":    194,
	"Atilde":   195,
	"Auml":     196,
	"Aring":    197,
	"AElig":    198,
	"Ccedil":   199,
	"Egrave":   200,
	"Eacute":   201,
	"Ecirc":    202,
	"Euml":     203,
	"Igrave":   204,
	"Iacute":   205,
	"Icirc":    206,
	"Iuml":     207,
	"ETH":      208,
	"Ntilde":   209,
	"Ograve":   210,
	"Oacute":   211,
	"Ocirc":    212,
	"Otilde":   213,
	"Ouml":     214,
	"times":    215,
	"Oslash":   216,
	"Ugrave":   217,
	"Uacute":   218,
	"Ucirc":    219,
	"Uuml":     220,
	"Yacute":   221,
	"THORN":    222,
	"szlig":    223,
	"agrave":   224,
	"aacute":   225,
	"acirc":    226,
	"atilde":   227,
	"auml":     228,
	"aring":    229,
	"aelig":    230,
	"ccedil":   231,
	"egrave":   232,
	"eacute":   233,
	"ecirc":    234,
	"euml":     235,
	"igrave":   236,
	"iacute":   237,
	"icirc":    238,
	"iuml":     239,
	"eth":      240,
	"ntilde":   241,
	"ograve":   242,
	"oacute":   243,
	"ocirc":    244,
	"otilde":   245,
	"ouml":     246,
	"divide":   247,
	"oslash":   248,
	"ugrave":   249,
	"uacute":   250,
	"ucirc":    251,
	"uuml":     252,
	"yacute":   253,
	"thorn":    254,
	"yuml":     255,
	"OElig":    338,
	"oelig":    339,
	"Scaron":   352,
	"scaron":   353,
	"Yuml":     376,
	"fnof":     402,
	"circ":     710,
	"tilde":    732,
	"Alpha":    913,
	"Beta":     914,
	"Gamma":    915,
	"Delta":    916,
	"Epsilon":  917,
	"Zeta":     918,
	"Eta":      919,
	"Theta":    920,
	"Iota":     921,
	"Kappa":    922,
	"Lambda":   923,
	"Mu":       924,
	"Nu":       925,
	"Xi":       926,
	"Omicron":  927,
	"Pi":       928,
	"Rho":      929,
	"Sigma":    931,
	"Tau":      932,
	"Upsilon":  933,
	"Phi":      934,
	"Chi":      935,
	"Psi":      936,
	"Omega":    937,
	"alpha":    945,
	"beta":     946,
	"gamma":    947,
	"delta":    948,
	"epsilon":  949,
	"zeta":     950,
	"eta":      951,
	"theta":    952,
	"iota":     953,
	"kappa":    954,
	"lambda":   955,
	"mu":       956,
	"nu":       957,
	"xi":       958,
	"omicron":  959,
	"pi":       960,
	"rho":      961,
	"sigmaf":   962,
	"sigma":    963,
	"tau":      964,
	"upsilon":  965,
	"phi":      966,
	"chi":      967,
	"psi":      968,
	"omega":    969,
	"thetasym": 977,
	"upsih":    978,
	"piv":      982,
	"ensp":     8194,
	"emsp":     8195,
	"thinsp":   8201,
	"zwnj":     8204,
	"zwj":      8205,
	"lrm":      8206,
	"rlm":      8207,
	"ndash":    8211,
	"mdash":    8212,
	"lsquo":    8216,
	"rsquo":    8217,
	"sbquo":    8218,
	"ldquo":    8220,
	"rdquo":    8221,
	"bdquo":    8222,
	"dagger":   8224,
	"Dagger":   8225,
	"bull":     8226,
	"hellip":   8230,
	"permil":   8240,
	"prime":    8242,
	"Prime":    8243,
	"lsaquo":   8249,
	"rsaquo":   8250,
	"oline":    8254,
	"frasl":    8260,
	"euro":     8364,
	"image":    8465,
	"weierp":   8472,
	"real":     8476,
	"trade":    8482,
	"alefsym":  8501,
	"larr":     8592,
	"uarr":     8593,
	"rarr":     8594,
	"darr":     8595,
	"harr":     8596,
	"crarr":    8629,
	"lArr":     8656,
	"uArr":     8657,
	"rArr":     8658,
	"dArr":     8659,
	"hArr":     8660,
	"forall":   8704,
	"part":     8706,
	"exist":    8707,
	"empty":    8709,
	"nabla":    8711,
	"isin":     8712,
	"notin":    8713,
	"ni":       8715,
	"prod":     8719,
	"sum":      8721,
	"minus":    8722,
	"lowast":   8727,
	"radic":    8730,
	"prop":     8733,
	"infin":    8734,
	"ang":      8736,
	"and":      8743,
	"or":       8744,
	"cap":      8745,
	"cup":      8746,
	"int":      8747,
	"there4":   8756,
	"sim":      8764,
	"cong":     8773,
	"asymp":    8776,
	"ne":       8800,
	"equiv":    8801,
	"le":       8804,
	"ge":       8805,
	"sub":      8834,
	"sup":      8835,
	"nsub":     8836,
	"sube":     8838,
	"supe":     8839,
	"oplus":    8853,
	"otimes":   8855,
	"perp":     8869,
	"sdot":     8901,
	"lceil":    8968,
	"rceil":    8969,
	"lfloor":   8970,
	"rfloor":   8971,
	"lang":     9001,
	"rang":     9002,
	"loz":      9674,
	"spades":   9824,
	"clubs":    9827,
	"hearts":   9829,
	"diams":    9830,
}

// html40Elements は libxml2 の html40ElementTable（名前, startTag, endTag, saveEndTag, empty, depr, dtd, isinline）。
var html40Elements = map[string]elemDesc{
	"a":          {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: true},
	"abbr":       {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: true},
	"acronym":    {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: true},
	"address":    {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: false},
	"applet":     {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: true},
	"area":       {startTag: 0, endTag: 2, saveEndTag: 2, empty: true, isInline: false},
	"b":          {startTag: 0, endTag: 3, saveEndTag: 0, empty: false, isInline: true},
	"base":       {startTag: 0, endTag: 2, saveEndTag: 2, empty: true, isInline: false},
	"basefont":   {startTag: 0, endTag: 2, saveEndTag: 2, empty: true, isInline: true},
	"bdo":        {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: true},
	"big":        {startTag: 0, endTag: 3, saveEndTag: 0, empty: false, isInline: true},
	"blockquote": {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: false},
	"body":       {startTag: 1, endTag: 1, saveEndTag: 0, empty: false, isInline: false},
	"br":         {startTag: 0, endTag: 2, saveEndTag: 2, empty: true, isInline: true},
	"button":     {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: true},
	"caption":    {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: false},
	"center":     {startTag: 0, endTag: 3, saveEndTag: 0, empty: false, isInline: false},
	"cite":       {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: true},
	"code":       {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: true},
	"col":        {startTag: 0, endTag: 2, saveEndTag: 2, empty: true, isInline: false},
	"colgroup":   {startTag: 0, endTag: 1, saveEndTag: 0, empty: false, isInline: false},
	"dd":         {startTag: 0, endTag: 1, saveEndTag: 0, empty: false, isInline: false},
	"del":        {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: true},
	"dfn":        {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: true},
	"dir":        {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: false},
	"div":        {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: false},
	"dl":         {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: false},
	"dt":         {startTag: 0, endTag: 1, saveEndTag: 0, empty: false, isInline: false},
	"em":         {startTag: 0, endTag: 3, saveEndTag: 0, empty: false, isInline: true},
	"embed":      {startTag: 0, endTag: 1, saveEndTag: 0, empty: false, isInline: true},
	"fieldset":   {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: false},
	"font":       {startTag: 0, endTag: 3, saveEndTag: 0, empty: false, isInline: true},
	"form":       {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: false},
	"frame":      {startTag: 0, endTag: 2, saveEndTag: 2, empty: true, isInline: false},
	"frameset":   {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: false},
	"h1":         {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: false},
	"h2":         {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: false},
	"h3":         {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: false},
	"h4":         {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: false},
	"h5":         {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: false},
	"h6":         {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: false},
	"head":       {startTag: 1, endTag: 1, saveEndTag: 0, empty: false, isInline: false},
	"hr":         {startTag: 0, endTag: 2, saveEndTag: 2, empty: true, isInline: false},
	"html":       {startTag: 1, endTag: 1, saveEndTag: 0, empty: false, isInline: false},
	"i":          {startTag: 0, endTag: 3, saveEndTag: 0, empty: false, isInline: true},
	"iframe":     {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: true},
	"img":        {startTag: 0, endTag: 2, saveEndTag: 2, empty: true, isInline: true},
	"input":      {startTag: 0, endTag: 2, saveEndTag: 2, empty: true, isInline: true},
	"ins":        {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: true},
	"isindex":    {startTag: 0, endTag: 2, saveEndTag: 2, empty: true, isInline: false},
	"kbd":        {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: true},
	"label":      {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: true},
	"legend":     {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: false},
	"li":         {startTag: 0, endTag: 1, saveEndTag: 1, empty: false, isInline: false},
	"link":       {startTag: 0, endTag: 2, saveEndTag: 2, empty: true, isInline: false},
	"map":        {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: true},
	"menu":       {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: false},
	"meta":       {startTag: 0, endTag: 2, saveEndTag: 2, empty: true, isInline: false},
	"noframes":   {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: false},
	"noscript":   {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: false},
	"object":     {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: true},
	"ol":         {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: false},
	"optgroup":   {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: false},
	"option":     {startTag: 0, endTag: 1, saveEndTag: 0, empty: false, isInline: false},
	"p":          {startTag: 0, endTag: 1, saveEndTag: 0, empty: false, isInline: false},
	"param":      {startTag: 0, endTag: 2, saveEndTag: 2, empty: true, isInline: false},
	"pre":        {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: false},
	"q":          {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: true},
	"s":          {startTag: 0, endTag: 3, saveEndTag: 0, empty: false, isInline: true},
	"samp":       {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: true},
	"script":     {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: true},
	"select":     {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: true},
	"small":      {startTag: 0, endTag: 3, saveEndTag: 0, empty: false, isInline: true},
	"span":       {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: true},
	"strike":     {startTag: 0, endTag: 3, saveEndTag: 0, empty: false, isInline: true},
	"strong":     {startTag: 0, endTag: 3, saveEndTag: 0, empty: false, isInline: true},
	"style":      {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: false},
	"sub":        {startTag: 0, endTag: 3, saveEndTag: 0, empty: false, isInline: true},
	"sup":        {startTag: 0, endTag: 3, saveEndTag: 0, empty: false, isInline: true},
	"table":      {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: false},
	"tbody":      {startTag: 1, endTag: 0, saveEndTag: 0, empty: false, isInline: false},
	"td":         {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: false},
	"textarea":   {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: true},
	"tfoot":      {startTag: 0, endTag: 1, saveEndTag: 0, empty: false, isInline: false},
	"th":         {startTag: 0, endTag: 1, saveEndTag: 0, empty: false, isInline: false},
	"thead":      {startTag: 0, endTag: 1, saveEndTag: 0, empty: false, isInline: false},
	"title":      {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: false},
	"tr":         {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: false},
	"tt":         {startTag: 0, endTag: 3, saveEndTag: 0, empty: false, isInline: true},
	"u":          {startTag: 0, endTag: 3, saveEndTag: 0, empty: false, isInline: true},
	"ul":         {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: false},
	"var":        {startTag: 0, endTag: 0, saveEndTag: 0, empty: false, isInline: true},
}

// htmlStartClose は libxml2 の htmlStartClose（{oldTag, newTag}: newTag 開始時に oldTag を自動で閉じる）。
var htmlStartClose = map[[2]string]bool{
	{"a", "a"}:               true,
	{"a", "fieldset"}:        true,
	{"a", "table"}:           true,
	{"a", "td"}:              true,
	{"a", "th"}:              true,
	{"address", "dd"}:        true,
	{"address", "dl"}:        true,
	{"address", "dt"}:        true,
	{"address", "form"}:      true,
	{"address", "li"}:        true,
	{"address", "ul"}:        true,
	{"b", "center"}:          true,
	{"b", "p"}:               true,
	{"b", "td"}:              true,
	{"b", "th"}:              true,
	{"big", "p"}:             true,
	{"caption", "col"}:       true,
	{"caption", "colgroup"}:  true,
	{"caption", "tbody"}:     true,
	{"caption", "tfoot"}:     true,
	{"caption", "thead"}:     true,
	{"caption", "tr"}:        true,
	{"col", "col"}:           true,
	{"col", "colgroup"}:      true,
	{"col", "tbody"}:         true,
	{"col", "tfoot"}:         true,
	{"col", "thead"}:         true,
	{"col", "tr"}:            true,
	{"colgroup", "colgroup"}: true,
	{"colgroup", "tbody"}:    true,
	{"colgroup", "tfoot"}:    true,
	{"colgroup", "thead"}:    true,
	{"colgroup", "tr"}:       true,
	{"dd", "dt"}:             true,
	{"dir", "dd"}:            true,
	{"dir", "dl"}:            true,
	{"dir", "dt"}:            true,
	{"dir", "form"}:          true,
	{"dir", "ul"}:            true,
	{"dl", "form"}:           true,
	{"dl", "li"}:             true,
	{"dt", "dd"}:             true,
	{"dt", "dl"}:             true,
	{"font", "center"}:       true,
	{"font", "td"}:           true,
	{"font", "th"}:           true,
	{"form", "form"}:         true,
	{"h1", "fieldset"}:       true,
	{"h1", "form"}:           true,
	{"h1", "li"}:             true,
	{"h1", "p"}:              true,
	{"h1", "table"}:          true,
	{"h2", "fieldset"}:       true,
	{"h2", "form"}:           true,
	{"h2", "li"}:             true,
	{"h2", "p"}:              true,
	{"h2", "table"}:          true,
	{"h3", "fieldset"}:       true,
	{"h3", "form"}:           true,
	{"h3", "li"}:             true,
	{"h3", "p"}:              true,
	{"h3", "table"}:          true,
	{"h4", "fieldset"}:       true,
	{"h4", "form"}:           true,
	{"h4", "li"}:             true,
	{"h4", "p"}:              true,
	{"h4", "table"}:          true,
	{"h5", "fieldset"}:       true,
	{"h5", "form"}:           true,
	{"h5", "li"}:             true,
	{"h5", "p"}:              true,
	{"h5", "table"}:          true,
	{"h6", "fieldset"}:       true,
	{"h6", "form"}:           true,
	{"h6", "li"}:             true,
	{"h6", "p"}:              true,
	{"h6", "table"}:          true,
	{"head", "a"}:            true,
	{"head", "abbr"}:         true,
	{"head", "acronym"}:      true,
	{"head", "address"}:      true,
	{"head", "b"}:            true,
	{"head", "bdo"}:          true,
	{"head", "big"}:          true,
	{"head", "blockquote"}:   true,
	{"head", "body"}:         true,
	{"head", "br"}:           true,
	{"head", "center"}:       true,
	{"head", "cite"}:         true,
	{"head", "code"}:         true,
	{"head", "dd"}:           true,
	{"head", "dfn"}:          true,
	{"head", "dir"}:          true,
	{"head", "div"}:          true,
	{"head", "dl"}:           true,
	{"head", "dt"}:           true,
	{"head", "em"}:           true,
	{"head", "fieldset"}:     true,
	{"head", "font"}:         true,
	{"head", "form"}:         true,
	{"head", "frameset"}:     true,
	{"head", "h1"}:           true,
	{"head", "h2"}:           true,
	{"head", "h3"}:           true,
	{"head", "h4"}:           true,
	{"head", "h5"}:           true,
	{"head", "h6"}:           true,
	{"head", "hr"}:           true,
	{"head", "i"}:            true,
	{"head", "iframe"}:       true,
	{"head", "img"}:          true,
	{"head", "kbd"}:          true,
	{"head", "li"}:           true,
	{"head", "listing"}:      true,
	{"head", "map"}:          true,
	{"head", "menu"}:         true,
	{"head", "ol"}:           true,
	{"head", "p"}:            true,
	{"head", "pre"}:          true,
	{"head", "q"}:            true,
	{"head", "s"}:            true,
	{"head", "samp"}:         true,
	{"head", "small"}:        true,
	{"head", "span"}:         true,
	{"head", "strike"}:       true,
	{"head", "strong"}:       true,
	{"head", "sub"}:          true,
	{"head", "sup"}:          true,
	{"head", "table"}:        true,
	{"head", "tt"}:           true,
	{"head", "u"}:            true,
	{"head", "ul"}:           true,
	{"head", "var"}:          true,
	{"head", "xmp"}:          true,
	{"hr", "form"}:           true,
	{"i", "center"}:          true,
	{"i", "p"}:               true,
	{"i", "td"}:              true,
	{"i", "th"}:              true,
	{"legend", "fieldset"}:   true,
	{"li", "li"}:             true,
	{"link", "body"}:         true,
	{"link", "frameset"}:     true,
	{"listing", "dd"}:        true,
	{"listing", "dl"}:        true,
	{"listing", "dt"}:        true,
	{"listing", "fieldset"}:  true,
	{"listing", "form"}:      true,
	{"listing", "li"}:        true,
	{"listing", "table"}:     true,
	{"listing", "ul"}:        true,
	{"menu", "dd"}:           true,
	{"menu", "dl"}:           true,
	{"menu", "dt"}:           true,
	{"menu", "form"}:         true,
	{"menu", "ul"}:           true,
	{"ol", "form"}:           true,
	{"option", "optgroup"}:   true,
	{"option", "option"}:     true,
	{"p", "address"}:         true,
	{"p", "blockquote"}:      true,
	{"p", "body"}:            true,
	{"p", "caption"}:         true,
	{"p", "center"}:          true,
	{"p", "col"}:             true,
	{"p", "colgroup"}:        true,
	{"p", "dd"}:              true,
	{"p", "dir"}:             true,
	{"p", "div"}:             true,
	{"p", "dl"}:              true,
	{"p", "dt"}:              true,
	{"p", "fieldset"}:        true,
	{"p", "form"}:            true,
	{"p", "frameset"}:        true,
	{"p", "h1"}:              true,
	{"p", "h2"}:              true,
	{"p", "h3"}:              true,
	{"p", "h4"}:              true,
	{"p", "h5"}:              true,
	{"p", "h6"}:              true,
	{"p", "head"}:            true,
	{"p", "hr"}:              true,
	{"p", "li"}:              true,
	{"p", "listing"}:         true,
	{"p", "menu"}:            true,
	{"p", "ol"}:              true,
	{"p", "p"}:               true,
	{"p", "pre"}:             true,
	{"p", "table"}:           true,
	{"p", "tbody"}:           true,
	{"p", "td"}:              true,
	{"p", "tfoot"}:           true,
	{"p", "th"}:              true,
	{"p", "title"}:           true,
	{"p", "tr"}:              true,
	{"p", "ul"}:              true,
	{"p", "xmp"}:             true,
	{"pre", "dd"}:            true,
	{"pre", "dl"}:            true,
	{"pre", "dt"}:            true,
	{"pre", "fieldset"}:      true,
	{"pre", "form"}:          true,
	{"pre", "li"}:            true,
	{"pre", "table"}:         true,
	{"pre", "ul"}:            true,
	{"s", "p"}:               true,
	{"script", "noscript"}:   true,
	{"small", "p"}:           true,
	{"span", "td"}:           true,
	{"span", "th"}:           true,
	{"strike", "p"}:          true,
	{"style", "body"}:        true,
	{"style", "frameset"}:    true,
	{"tbody", "tbody"}:       true,
	{"tbody", "tfoot"}:       true,
	{"td", "tbody"}:          true,
	{"td", "td"}:             true,
	{"td", "tfoot"}:          true,
	{"td", "th"}:             true,
	{"td", "tr"}:             true,
	{"tfoot", "tbody"}:       true,
	{"th", "tbody"}:          true,
	{"th", "td"}:             true,
	{"th", "tfoot"}:          true,
	{"th", "th"}:             true,
	{"th", "tr"}:             true,
	{"thead", "tbody"}:       true,
	{"thead", "tfoot"}:       true,
	{"title", "body"}:        true,
	{"title", "frameset"}:    true,
	{"tr", "tbody"}:          true,
	{"tr", "tfoot"}:          true,
	{"tr", "tr"}:             true,
	{"tt", "p"}:              true,
	{"u", "p"}:               true,
	{"u", "td"}:              true,
	{"u", "th"}:              true,
	{"ul", "address"}:        true,
	{"ul", "form"}:           true,
	{"ul", "menu"}:           true,
	{"ul", "pre"}:            true,
	{"xmp", "dd"}:            true,
	{"xmp", "dl"}:            true,
	{"xmp", "dt"}:            true,
	{"xmp", "fieldset"}:      true,
	{"xmp", "form"}:          true,
	{"xmp", "li"}:            true,
	{"xmp", "table"}:         true,
	{"xmp", "ul"}:            true,
}
