-- Code generated by internal/db/internal/migrationgen from migrations/src/00002_perf_indexes.sql.tmpl. DO NOT EDIT.

-- +goose Up

-- プロジェクト (とその子孫) のチケットをステータスで絞る件数・一覧・集計
-- (チケット一覧の件数、プロジェクト概要のトラッカー別件数、ガントチャート等)。
-- issues_project_id (project_id) はこのインデックスの先頭列で代替できるので削除する。
CREATE INDEX issues_project_status ON issues (project_id, status_id);
DROP INDEX issues_project_id;

-- +goose Down
CREATE INDEX issues_project_id ON issues (project_id);
DROP INDEX issues_project_status;
