-- Code generated by internal/db/internal/migrationgen from migrations/src/00001_initial_schema.sql.tmpl. DO NOT EDIT.

-- +goose Up

-- =====================================================================
-- 認証ソース (Redmine auth_sources を一般化: kind = ldap / oidc)
-- =====================================================================
CREATE TABLE auth_sources (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  kind TEXT NOT NULL CHECK (kind IN ('ldap', 'oidc')),
  name TEXT NOT NULL,
  enabled INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
  position INTEGER NOT NULL DEFAULT 1,
  onthefly_register INTEGER NOT NULL DEFAULT 0 CHECK (onthefly_register IN (0, 1)),
  -- LDAP: host, port, tls(ldaps), starttls, verify_peer, account, base_dn, filter, timeout,
  --       attr_login/attr_firstname/attr_lastname/attr_mail, ...
  -- OIDC: issuer, client_id, scopes, claim マッピング, ...
  config TEXT CHECK (json_valid(config)) NOT NULL DEFAULT '{}',
  -- 暗号化対象の秘密値 (LDAP の account_password / OIDC の client_secret)。
  -- Redmine 形式 "aes-256-cbc:<b64>--<b64iv>" もそのまま保持できる。
  secret TEXT,
  created_at TEXT CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL,
  updated_at TEXT CHECK (updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL
);
CREATE UNIQUE INDEX auth_sources_name ON auth_sources (name);

-- =====================================================================
-- プリンシパル (Redmine users の STI を principals + user_accounts に分割)
-- =====================================================================
CREATE TABLE principals (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  kind TEXT NOT NULL CHECK (kind IN ('user', 'anonymous_user', 'group', 'group_anonymous', 'group_non_member')),
  -- 0=匿名, 1=有効, 2=登録済(未有効化), 3=ロック
  status INTEGER NOT NULL DEFAULT 1 CHECK (status IN (0, 1, 2, 3)),
  firstname TEXT NOT NULL DEFAULT '',
  lastname TEXT NOT NULL DEFAULT '',
  -- グループ表示名 (旧 users.lastname)。ユーザは ''。
  name TEXT NOT NULL DEFAULT '',
  -- グループに対する 2FA 必須 (旧 users.twofa_required)
  twofa_required INTEGER NOT NULL DEFAULT 0 CHECK (twofa_required IN (0, 1)),
  created_at TEXT CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL,
  updated_at TEXT CHECK (updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL
);
CREATE INDEX principals_kind ON principals (kind);
CREATE INDEX principals_kind_status ON principals (kind, status);
-- 組込プリンシパルは各 1 行のみ
CREATE UNIQUE INDEX principals_builtin_kind ON principals (kind)
  WHERE kind IN ('anonymous_user', 'group_anonymous', 'group_non_member');

CREATE TABLE user_accounts (
  principal_id INTEGER PRIMARY KEY REFERENCES principals (id) ON DELETE CASCADE,
  login TEXT NOT NULL DEFAULT '',
  -- "redmine-sha1$<salt>$<hex>" / "$argon2id$..." 等の PHC 風文字列。NULL = パスワードなし
  password_hash TEXT,
  password_changed_at TEXT CHECK (password_changed_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z'),
  must_change_password INTEGER NOT NULL DEFAULT 0 CHECK (must_change_password IN (0, 1)),
  admin INTEGER NOT NULL DEFAULT 0 CHECK (admin IN (0, 1)),
  -- NULL = 既定言語
  language TEXT,
  auth_source_id INTEGER REFERENCES auth_sources (id) ON DELETE RESTRICT,
  last_login_at TEXT CHECK (last_login_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z'),
  twofa_scheme TEXT CHECK (twofa_scheme IN ('totp')),
  -- 暗号化された TOTP シークレット
  twofa_totp_key TEXT,
  -- 最後に検証成功した TOTP タイムステップ (UNIX 秒)
  twofa_totp_last_used_at INTEGER
);
CREATE UNIQUE INDEX user_accounts_login ON user_accounts (lower(login)) WHERE login <> '';
CREATE INDEX user_accounts_auth_source_id ON user_accounts (auth_source_id);

CREATE TABLE email_addresses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL REFERENCES user_accounts (principal_id) ON DELETE CASCADE,
  address TEXT NOT NULL,
  is_default INTEGER NOT NULL DEFAULT 0 CHECK (is_default IN (0, 1)),
  notify INTEGER NOT NULL DEFAULT 1 CHECK (notify IN (0, 1)),
  created_at TEXT CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL,
  updated_at TEXT CHECK (updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL
);
CREATE INDEX email_addresses_user_id ON email_addresses (user_id);
CREATE UNIQUE INDEX email_addresses_address ON email_addresses (lower(address));
CREATE UNIQUE INDEX email_addresses_default ON email_addresses (user_id) WHERE is_default = 1;

CREATE TABLE group_users (
  group_id INTEGER NOT NULL REFERENCES principals (id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES user_accounts (principal_id) ON DELETE CASCADE,
  PRIMARY KEY (group_id, user_id)
);
CREATE INDEX group_users_user_id ON group_users (user_id);

-- LDAP / OIDC のグループ → buropher グループの対応表 (buropher 拡張)
CREATE TABLE auth_source_group_mappings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  auth_source_id INTEGER NOT NULL REFERENCES auth_sources (id) ON DELETE CASCADE,
  -- LDAP グループ DN / OIDC groups クレームの値
  external_group TEXT NOT NULL,
  group_id INTEGER NOT NULL REFERENCES principals (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX auth_source_group_mappings_unique ON auth_source_group_mappings (auth_source_id, external_group, group_id);
CREATE INDEX auth_source_group_mappings_group_id ON auth_source_group_mappings (group_id);

-- 外部 ID 連携 (OIDC / Discord)
CREATE TABLE user_identities (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL REFERENCES user_accounts (principal_id) ON DELETE CASCADE,
  -- 'oidc:<auth_source_id>' / 'discord'
  provider TEXT NOT NULL,
  auth_source_id INTEGER REFERENCES auth_sources (id) ON DELETE CASCADE,
  subject TEXT NOT NULL,
  email TEXT,
  raw_claims TEXT CHECK (json_valid(raw_claims)),
  created_at TEXT CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL,
  last_login_at TEXT CHECK (last_login_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z')
);
CREATE UNIQUE INDEX user_identities_provider_subject ON user_identities (provider, subject);
CREATE INDEX user_identities_user_id ON user_identities (user_id);

-- Redmine tokens のうち存続するもの (session は sessions、twofa_backup_code は twofa_backup_codes へ)
CREATE TABLE tokens (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL REFERENCES user_accounts (principal_id) ON DELETE CASCADE,
  action TEXT NOT NULL CHECK (action IN ('api', 'feeds', 'autologin', 'recovery', 'register', 'twofa_session')),
  -- api/feeds は「キーを表示」機能のため平文保持
  value TEXT NOT NULL,
  created_at TEXT CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL,
  updated_at TEXT CHECK (updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z')
);
CREATE UNIQUE INDEX tokens_value ON tokens (value);
CREATE INDEX tokens_user_id_action ON tokens (user_id, action);

CREATE TABLE twofa_backup_codes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL REFERENCES user_accounts (principal_id) ON DELETE CASCADE,
  -- SHA-256 hex。使用時に行を削除する (Redmine と同じ)
  code_digest TEXT NOT NULL,
  created_at TEXT CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL
);
CREATE UNIQUE INDEX twofa_backup_codes_user_code ON twofa_backup_codes (user_id, code_digest);

CREATE TABLE sessions (
  -- Cookie に載せるランダムトークンの SHA-256 hex
  id TEXT PRIMARY KEY,
  -- NULL = 未ログイン (匿名) セッション
  user_id INTEGER REFERENCES user_accounts (principal_id) ON DELETE CASCADE,
  created_at TEXT CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL,
  last_seen_at TEXT CHECK (last_seen_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL,
  expires_at TEXT CHECK (expires_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z'),
  sudo_until TEXT CHECK (sudo_until GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z'),
  -- パスワード認証済みで 2FA 未完了
  twofa_pending INTEGER NOT NULL DEFAULT 0 CHECK (twofa_pending IN (0, 1)),
  ip TEXT,
  user_agent TEXT,
  -- CSRF トークン, back_url, flash 等
  data TEXT CHECK (json_valid(data)) NOT NULL DEFAULT '{}'
);
CREATE INDEX sessions_user_id ON sessions (user_id);
CREATE INDEX sessions_expires_at ON sessions (expires_at);
CREATE INDEX sessions_last_seen_at ON sessions (last_seen_at);

-- =====================================================================
-- ステータス・トラッカー
-- =====================================================================
CREATE TABLE issue_statuses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  description TEXT,
  is_closed INTEGER NOT NULL DEFAULT 0 CHECK (is_closed IN (0, 1)),
  position INTEGER NOT NULL DEFAULT 1,
  default_done_ratio INTEGER CHECK (default_done_ratio BETWEEN 0 AND 100)
);
CREATE UNIQUE INDEX issue_statuses_name ON issue_statuses (name);
CREATE INDEX issue_statuses_is_closed ON issue_statuses (is_closed);
CREATE INDEX issue_statuses_position ON issue_statuses (position);

CREATE TABLE trackers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  description TEXT,
  position INTEGER NOT NULL DEFAULT 1,
  is_in_roadmap INTEGER NOT NULL DEFAULT 1 CHECK (is_in_roadmap IN (0, 1)),
  default_status_id INTEGER NOT NULL REFERENCES issue_statuses (id) ON DELETE RESTRICT,
  -- 無効化された標準フィールド名の配列 (旧 fields_bits)
  disabled_core_fields TEXT CHECK (json_valid(disabled_core_fields)) NOT NULL DEFAULT '[]'
);
CREATE UNIQUE INDEX trackers_name ON trackers (name);
CREATE INDEX trackers_position ON trackers (position);

-- =====================================================================
-- プロジェクト
-- =====================================================================
CREATE TABLE projects (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  parent_id INTEGER REFERENCES projects (id) DEFERRABLE INITIALLY DEFERRED,
  name TEXT NOT NULL,
  identifier TEXT NOT NULL,
  description TEXT,
  homepage TEXT,
  is_public INTEGER NOT NULL DEFAULT 1 CHECK (is_public IN (0, 1)),
  -- 1=有効, 5=終了, 9=アーカイブ, 10=削除予約
  status INTEGER NOT NULL DEFAULT 1 CHECK (status IN (1, 5, 9, 10)),
  inherit_members INTEGER NOT NULL DEFAULT 0 CHECK (inherit_members IN (0, 1)),
  -- 兄弟間の表示順 (Redmine の lft 順を保持する。移行時は旧 lft 順、新規・改名・移動時は名前で挿入位置を決める)
  position INTEGER NOT NULL DEFAULT 0,
  default_version_id INTEGER REFERENCES versions (id) ON DELETE SET NULL,
  default_assigned_to_id INTEGER REFERENCES principals (id) ON DELETE SET NULL,
  default_issue_query_id INTEGER REFERENCES queries (id) ON DELETE SET NULL,
  created_at TEXT CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL,
  updated_at TEXT CHECK (updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL,
  CHECK (parent_id IS NULL OR parent_id <> id)
);
CREATE UNIQUE INDEX projects_identifier ON projects (identifier);
CREATE INDEX projects_parent_id ON projects (parent_id, position);
CREATE INDEX projects_status ON projects (status);
CREATE INDEX projects_default_version_id ON projects (default_version_id);
CREATE INDEX projects_default_assigned_to_id ON projects (default_assigned_to_id);
CREATE INDEX projects_default_issue_query_id ON projects (default_issue_query_id);

-- 閉包テーブル (自分自身 depth=0 の行を含む)
CREATE TABLE project_closure (
  ancestor_id INTEGER NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
  descendant_id INTEGER NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
  depth INTEGER NOT NULL CHECK (depth >= 0),
  PRIMARY KEY (ancestor_id, descendant_id)
);
CREATE INDEX project_closure_descendant ON project_closure (descendant_id, depth);

-- 旧 enabled_modules (id はニュースモジュールのウォッチャ参照のため保持)
CREATE TABLE project_modules (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
  name TEXT NOT NULL CHECK (name IN ('issue_tracking', 'time_tracking', 'news', 'documents', 'files', 'wiki', 'repository', 'boards', 'calendar', 'gantt'))
);
CREATE UNIQUE INDEX project_modules_project_name ON project_modules (project_id, name);

CREATE TABLE project_trackers (
  project_id INTEGER NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
  tracker_id INTEGER NOT NULL REFERENCES trackers (id) ON DELETE CASCADE,
  PRIMARY KEY (project_id, tracker_id)
);
CREATE INDEX project_trackers_tracker_id ON project_trackers (tracker_id);

-- =====================================================================
-- 列挙 (旧 enumerations の STI を 3 テーブルに分割)
-- =====================================================================
CREATE TABLE issue_priorities (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  position INTEGER NOT NULL DEFAULT 1,
  is_default INTEGER NOT NULL DEFAULT 0 CHECK (is_default IN (0, 1)),
  active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
  -- CSS 用の導出値 (lowest/default/high2/highest 等)
  position_name TEXT
);
CREATE UNIQUE INDEX issue_priorities_name ON issue_priorities (name);
CREATE INDEX issue_priorities_position ON issue_priorities (position);

CREATE TABLE document_categories (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  position INTEGER NOT NULL DEFAULT 1,
  is_default INTEGER NOT NULL DEFAULT 0 CHECK (is_default IN (0, 1)),
  active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1))
);
CREATE UNIQUE INDEX document_categories_name ON document_categories (name);
CREATE INDEX document_categories_position ON document_categories (position);

CREATE TABLE time_entry_activities (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  position INTEGER NOT NULL DEFAULT 1,
  is_default INTEGER NOT NULL DEFAULT 0 CHECK (is_default IN (0, 1)),
  active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
  -- プロジェクト別上書き行のみ非 NULL
  project_id INTEGER REFERENCES projects (id) ON DELETE CASCADE,
  parent_id INTEGER REFERENCES time_entry_activities (id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  CHECK ((project_id IS NULL) = (parent_id IS NULL))
);
CREATE UNIQUE INDEX time_entry_activities_name ON time_entry_activities (COALESCE(project_id, 0), name);
CREATE INDEX time_entry_activities_project_id ON time_entry_activities (project_id);
CREATE INDEX time_entry_activities_parent_id ON time_entry_activities (parent_id);
CREATE INDEX time_entry_activities_position ON time_entry_activities (position);

-- =====================================================================
-- ロール・権限
-- =====================================================================
CREATE TABLE roles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  position INTEGER NOT NULL DEFAULT 1,
  assignable INTEGER NOT NULL DEFAULT 1 CHECK (assignable IN (0, 1)),
  -- 0=通常, 1=非メンバー, 2=匿名
  builtin INTEGER NOT NULL DEFAULT 0 CHECK (builtin IN (0, 1, 2)),
  issues_visibility TEXT NOT NULL DEFAULT 'default' CHECK (issues_visibility IN ('all', 'default', 'own')),
  users_visibility TEXT NOT NULL DEFAULT 'members_of_visible_projects' CHECK (users_visibility IN ('all', 'members_of_visible_projects')),
  time_entries_visibility TEXT NOT NULL DEFAULT 'all' CHECK (time_entries_visibility IN ('all', 'own')),
  all_roles_managed INTEGER NOT NULL DEFAULT 1 CHECK (all_roles_managed IN (0, 1)),
  default_time_entry_activity_id INTEGER REFERENCES time_entry_activities (id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX roles_name ON roles (name);
CREATE UNIQUE INDEX roles_builtin ON roles (builtin) WHERE builtin <> 0;
CREATE INDEX roles_position ON roles (position);
CREATE INDEX roles_default_time_entry_activity_id ON roles (default_time_entry_activity_id);

CREATE TABLE role_permissions (
  role_id INTEGER NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
  permission TEXT NOT NULL,
  -- トラッカー限定可能な権限で false の場合は role_permission_trackers のトラッカーのみ
  all_trackers INTEGER NOT NULL DEFAULT 1 CHECK (all_trackers IN (0, 1)),
  -- roles.permissions（YAML 配列）での並び順。API などは保存順で出す（Role#permissions= はフォーム順、add_permission! は末尾追加）
  position INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (role_id, permission)
);
CREATE INDEX role_permissions_permission ON role_permissions (permission);

CREATE TABLE role_permission_trackers (
  role_id INTEGER NOT NULL,
  permission TEXT NOT NULL,
  tracker_id INTEGER NOT NULL REFERENCES trackers (id) ON DELETE CASCADE,
  PRIMARY KEY (role_id, permission, tracker_id),
  FOREIGN KEY (role_id, permission) REFERENCES role_permissions (role_id, permission) ON DELETE CASCADE
);
CREATE INDEX role_permission_trackers_tracker_id ON role_permission_trackers (tracker_id);

CREATE TABLE roles_managed_roles (
  role_id INTEGER NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
  managed_role_id INTEGER NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
  PRIMARY KEY (role_id, managed_role_id)
);
CREATE INDEX roles_managed_roles_managed_role_id ON roles_managed_roles (managed_role_id);

-- =====================================================================
-- メンバー
-- =====================================================================
CREATE TABLE members (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
  principal_id INTEGER NOT NULL REFERENCES principals (id) ON DELETE CASCADE,
  created_at TEXT CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL,
  UNIQUE (principal_id, project_id)
);
CREATE INDEX members_project_id ON members (project_id);

CREATE TABLE member_roles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  member_id INTEGER NOT NULL REFERENCES members (id) ON DELETE CASCADE,
  role_id INTEGER NOT NULL REFERENCES roles (id) ON DELETE RESTRICT,
  -- 派生元の member_roles.id (グループ / 親プロジェクトからの継承)
  inherited_from INTEGER REFERENCES member_roles (id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX member_roles_member_id ON member_roles (member_id);
CREATE INDEX member_roles_role_id ON member_roles (role_id);
CREATE INDEX member_roles_inherited_from ON member_roles (inherited_from);
CREATE UNIQUE INDEX member_roles_direct_unique ON member_roles (member_id, role_id) WHERE inherited_from IS NULL;
CREATE UNIQUE INDEX member_roles_inherited_unique ON member_roles (member_id, role_id, inherited_from) WHERE inherited_from IS NOT NULL;

-- 通知設定 'selected' の対象プロジェクト (旧 members.mail_notification)。
-- メンバーでなくなると自動で消えるよう members に複合 FK を張る。
CREATE TABLE user_notified_projects (
  user_id INTEGER NOT NULL REFERENCES user_accounts (principal_id) ON DELETE CASCADE,
  project_id INTEGER NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, project_id),
  FOREIGN KEY (user_id, project_id) REFERENCES members (principal_id, project_id) ON DELETE CASCADE
);
CREATE INDEX user_notified_projects_project_id ON user_notified_projects (project_id);

-- =====================================================================
-- カスタムフィールド
-- =====================================================================
CREATE TABLE custom_fields (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  owner_kind TEXT NOT NULL CHECK (owner_kind IN ('issue', 'project', 'time_entry', 'version', 'document', 'user', 'group', 'issue_priority', 'time_entry_activity', 'document_category')),
  name TEXT NOT NULL,
  description TEXT,
  field_format TEXT NOT NULL CHECK (field_format IN ('string', 'text', 'link', 'int', 'float', 'date', 'list', 'bool', 'enumeration', 'user', 'version', 'attachment', 'progressbar')),
  regexp TEXT,
  min_length INTEGER,
  max_length INTEGER,
  is_required INTEGER NOT NULL DEFAULT 0 CHECK (is_required IN (0, 1)),
  is_for_all INTEGER NOT NULL DEFAULT 0 CHECK (is_for_all IN (0, 1)),
  is_filter INTEGER NOT NULL DEFAULT 0 CHECK (is_filter IN (0, 1)),
  searchable INTEGER NOT NULL DEFAULT 0 CHECK (searchable IN (0, 1)),
  default_value TEXT,
  editable INTEGER NOT NULL DEFAULT 1 CHECK (editable IN (0, 1)),
  visible INTEGER NOT NULL DEFAULT 1 CHECK (visible IN (0, 1)),
  multiple INTEGER NOT NULL DEFAULT 0 CHECK (multiple IN (0, 1)),
  position INTEGER NOT NULL DEFAULT 1,
  -- list 形式の選択肢 (文字列配列)
  possible_values TEXT CHECK (json_valid(possible_values)),
  -- 旧 format_store (url_pattern, text_formatting, edit_tag_style, user_role, ...)
  format_settings TEXT CHECK (json_valid(format_settings)) NOT NULL DEFAULT '{}'
);
CREATE UNIQUE INDEX custom_fields_owner_name ON custom_fields (owner_kind, name);
CREATE INDEX custom_fields_owner_position ON custom_fields (owner_kind, position);

CREATE TABLE custom_field_enumerations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  custom_field_id INTEGER NOT NULL REFERENCES custom_fields (id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
  position INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX custom_field_enumerations_custom_field_id ON custom_field_enumerations (custom_field_id, position);

CREATE TABLE custom_fields_projects (
  custom_field_id INTEGER NOT NULL REFERENCES custom_fields (id) ON DELETE CASCADE,
  project_id INTEGER NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
  PRIMARY KEY (custom_field_id, project_id)
);
CREATE INDEX custom_fields_projects_project_id ON custom_fields_projects (project_id);

CREATE TABLE custom_fields_roles (
  custom_field_id INTEGER NOT NULL REFERENCES custom_fields (id) ON DELETE CASCADE,
  role_id INTEGER NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
  PRIMARY KEY (custom_field_id, role_id)
);
CREATE INDEX custom_fields_roles_role_id ON custom_fields_roles (role_id);

CREATE TABLE custom_fields_trackers (
  custom_field_id INTEGER NOT NULL REFERENCES custom_fields (id) ON DELETE CASCADE,
  tracker_id INTEGER NOT NULL REFERENCES trackers (id) ON DELETE CASCADE,
  PRIMARY KEY (custom_field_id, tracker_id)
);
CREATE INDEX custom_fields_trackers_tracker_id ON custom_fields_trackers (tracker_id);

-- ポリモーフィック (customized_kind + customized_id)。所有者削除時はアプリで連鎖削除する。
CREATE TABLE custom_values (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  customized_kind TEXT NOT NULL CHECK (customized_kind IN ('issue', 'project', 'time_entry', 'version', 'document', 'principal', 'enumeration')),
  customized_id INTEGER NOT NULL,
  custom_field_id INTEGER NOT NULL REFERENCES custom_fields (id) ON DELETE CASCADE,
  -- 複数値は 1 値 1 行。未入力は NULL
  value TEXT
);
CREATE INDEX custom_values_customized ON custom_values (customized_kind, customized_id, custom_field_id);
CREATE INDEX custom_values_custom_field_id ON custom_values (custom_field_id);

-- =====================================================================
-- ワークフロー (旧 workflows の STI を分割)
-- =====================================================================
CREATE TABLE workflow_transitions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tracker_id INTEGER NOT NULL REFERENCES trackers (id) ON DELETE CASCADE,
  role_id INTEGER NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
  -- NULL = 新規チケット作成時 (旧 old_status_id = 0)
  old_status_id INTEGER REFERENCES issue_statuses (id) ON DELETE CASCADE,
  new_status_id INTEGER NOT NULL REFERENCES issue_statuses (id) ON DELETE CASCADE,
  author INTEGER NOT NULL DEFAULT 0 CHECK (author IN (0, 1)),
  assignee INTEGER NOT NULL DEFAULT 0 CHECK (assignee IN (0, 1))
);
CREATE UNIQUE INDEX workflow_transitions_unique ON workflow_transitions (tracker_id, role_id, COALESCE(old_status_id, 0), new_status_id, author, assignee);
CREATE INDEX workflow_transitions_role_tracker_old ON workflow_transitions (role_id, tracker_id, old_status_id);
CREATE INDEX workflow_transitions_old_status_id ON workflow_transitions (old_status_id);
CREATE INDEX workflow_transitions_new_status_id ON workflow_transitions (new_status_id);

CREATE TABLE workflow_field_rules (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tracker_id INTEGER NOT NULL REFERENCES trackers (id) ON DELETE CASCADE,
  role_id INTEGER NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
  status_id INTEGER NOT NULL REFERENCES issue_statuses (id) ON DELETE CASCADE,
  core_field TEXT CHECK (core_field IN ('project_id', 'tracker_id', 'subject', 'is_private', 'assigned_to_id', 'category_id', 'fixed_version_id', 'parent_issue_id', 'start_date', 'due_date', 'estimated_hours', 'done_ratio', 'description', 'priority_id')),
  custom_field_id INTEGER REFERENCES custom_fields (id) ON DELETE CASCADE,
  rule TEXT NOT NULL CHECK (rule IN ('readonly', 'required')),
  CHECK ((core_field IS NULL) <> (custom_field_id IS NULL))
);
CREATE UNIQUE INDEX workflow_field_rules_unique ON workflow_field_rules (tracker_id, role_id, status_id, COALESCE(core_field, ''), COALESCE(custom_field_id, 0));
CREATE INDEX workflow_field_rules_role_tracker_status ON workflow_field_rules (role_id, tracker_id, status_id);
CREATE INDEX workflow_field_rules_status_id ON workflow_field_rules (status_id);
CREATE INDEX workflow_field_rules_custom_field_id ON workflow_field_rules (custom_field_id);

-- =====================================================================
-- バージョン・カテゴリ
-- =====================================================================
CREATE TABLE versions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  effective_date TEXT CHECK (effective_date GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'),
  wiki_page_title TEXT,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'locked', 'closed')),
  sharing TEXT NOT NULL DEFAULT 'none' CHECK (sharing IN ('none', 'descendants', 'hierarchy', 'tree', 'system')),
  created_at TEXT CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL,
  updated_at TEXT CHECK (updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL
);
CREATE UNIQUE INDEX versions_project_name ON versions (project_id, name);
CREATE INDEX versions_sharing ON versions (sharing);

CREATE TABLE issue_categories (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  assigned_to_id INTEGER REFERENCES principals (id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX issue_categories_project_name ON issue_categories (project_id, name);
CREATE INDEX issue_categories_assigned_to_id ON issue_categories (assigned_to_id);

-- =====================================================================
-- チケット
-- =====================================================================
CREATE TABLE issues (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
  tracker_id INTEGER NOT NULL REFERENCES trackers (id) ON DELETE RESTRICT,
  status_id INTEGER NOT NULL REFERENCES issue_statuses (id) ON DELETE RESTRICT,
  priority_id INTEGER NOT NULL REFERENCES issue_priorities (id) ON DELETE RESTRICT,
  author_id INTEGER NOT NULL REFERENCES principals (id) ON DELETE RESTRICT,
  assigned_to_id INTEGER REFERENCES principals (id) ON DELETE SET NULL,
  category_id INTEGER REFERENCES issue_categories (id) ON DELETE SET NULL,
  fixed_version_id INTEGER REFERENCES versions (id) ON DELETE SET NULL,
  parent_id INTEGER REFERENCES issues (id) DEFERRABLE INITIALLY DEFERRED,
  -- ルート自身は root_id = id
  root_id INTEGER NOT NULL REFERENCES issues (id) DEFERRABLE INITIALLY DEFERRED,
  -- ルートから自身までの ID を 10 桁ゼロ埋め + '/' で連結 (例 '0000000012/0000000045/')
  hier_path TEXT NOT NULL,
  subject TEXT NOT NULL,
  description TEXT,
  start_date TEXT CHECK (start_date GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'),
  due_date TEXT CHECK (due_date GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'),
  done_ratio INTEGER NOT NULL DEFAULT 0 CHECK (done_ratio BETWEEN 0 AND 100),
  estimated_hours REAL,
  is_private INTEGER NOT NULL DEFAULT 0 CHECK (is_private IN (0, 1)),
  lock_version INTEGER NOT NULL DEFAULT 0,
  created_at TEXT CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL,
  updated_at TEXT CHECK (updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL,
  closed_at TEXT CHECK (closed_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z'),
  CHECK (parent_id IS NULL OR parent_id <> id)
);
CREATE INDEX issues_project_id ON issues (project_id);
CREATE INDEX issues_tracker_id ON issues (tracker_id);
CREATE INDEX issues_status_id ON issues (status_id);
CREATE INDEX issues_priority_id ON issues (priority_id);
CREATE INDEX issues_author_id ON issues (author_id);
CREATE INDEX issues_assigned_to_id ON issues (assigned_to_id);
CREATE INDEX issues_category_id ON issues (category_id);
CREATE INDEX issues_fixed_version_id ON issues (fixed_version_id);
CREATE INDEX issues_parent_id ON issues (parent_id);
CREATE INDEX issues_root_hier_path ON issues (root_id, hier_path);
CREATE INDEX issues_hier_path ON issues (hier_path);
CREATE INDEX issues_created_at ON issues (created_at);
CREATE INDEX issues_updated_at ON issues (updated_at);

CREATE TABLE issue_relations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  issue_from_id INTEGER NOT NULL REFERENCES issues (id) ON DELETE CASCADE,
  issue_to_id INTEGER NOT NULL REFERENCES issues (id) ON DELETE CASCADE,
  relation_type TEXT NOT NULL CHECK (relation_type IN ('relates', 'duplicates', 'duplicated', 'blocks', 'blocked', 'precedes', 'follows', 'copied_to', 'copied_from')),
  delay INTEGER,
  CHECK (issue_from_id <> issue_to_id)
);
CREATE UNIQUE INDEX issue_relations_from_to ON issue_relations (issue_from_id, issue_to_id);
CREATE INDEX issue_relations_issue_to_id ON issue_relations (issue_to_id);

CREATE TABLE issue_journals (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  issue_id INTEGER NOT NULL REFERENCES issues (id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES principals (id) ON DELETE RESTRICT,
  -- 変更のみのジャーナルは NULL
  notes TEXT,
  private_notes INTEGER NOT NULL DEFAULT 0 CHECK (private_notes IN (0, 1)),
  created_at TEXT CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL,
  -- 注記の編集日時・編集者
  updated_at TEXT CHECK (updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z'),
  updated_by_id INTEGER REFERENCES principals (id) ON DELETE SET NULL
);
CREATE INDEX issue_journals_issue_id ON issue_journals (issue_id, id);
CREATE INDEX issue_journals_user_id ON issue_journals (user_id);
CREATE INDEX issue_journals_created_at ON issue_journals (created_at);
CREATE INDEX issue_journals_updated_by_id ON issue_journals (updated_by_id);

CREATE TABLE issue_journal_details (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  journal_id INTEGER NOT NULL REFERENCES issue_journals (id) ON DELETE CASCADE,
  property TEXT NOT NULL CHECK (property IN ('attr', 'cf', 'attachment', 'relation')),
  prop_key TEXT NOT NULL,
  -- property='cf' のとき prop_key を数値化した冗長列 (FK なし: 削除済み CF の履歴も保持)
  custom_field_id INTEGER,
  old_value TEXT,
  value TEXT,
  CHECK (property <> 'cf' OR custom_field_id IS NOT NULL)
);
CREATE INDEX issue_journal_details_journal_id ON issue_journal_details (journal_id);
CREATE INDEX issue_journal_details_property ON issue_journal_details (property, prop_key);

-- ポリモーフィック (watchable_kind + watchable_id)
CREATE TABLE watchers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  watchable_kind TEXT NOT NULL CHECK (watchable_kind IN ('issue', 'news', 'board', 'message', 'wiki', 'wiki_page', 'project_module')),
  watchable_id INTEGER NOT NULL,
  principal_id INTEGER NOT NULL REFERENCES principals (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX watchers_unique ON watchers (watchable_kind, watchable_id, principal_id);
CREATE INDEX watchers_principal_kind ON watchers (principal_id, watchable_kind);

-- =====================================================================
-- 工数
-- =====================================================================
CREATE TABLE time_entries (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
  -- 作業者
  user_id INTEGER NOT NULL REFERENCES principals (id) ON DELETE RESTRICT,
  -- 記録者
  author_id INTEGER NOT NULL REFERENCES principals (id) ON DELETE RESTRICT,
  issue_id INTEGER REFERENCES issues (id) ON DELETE CASCADE,
  hours REAL NOT NULL,
  comments TEXT,
  activity_id INTEGER NOT NULL REFERENCES time_entry_activities (id) ON DELETE RESTRICT,
  spent_on TEXT CHECK (spent_on GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]') NOT NULL,
  tyear INTEGER NOT NULL,
  tmonth INTEGER NOT NULL,
  -- ISO 週番号
  tweek INTEGER NOT NULL,
  created_at TEXT CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL,
  updated_at TEXT CHECK (updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL
);
CREATE INDEX time_entries_project_id ON time_entries (project_id, spent_on);
CREATE INDEX time_entries_issue_id ON time_entries (issue_id);
CREATE INDEX time_entries_user_id ON time_entries (user_id);
CREATE INDEX time_entries_author_id ON time_entries (author_id);
CREATE INDEX time_entries_activity_id ON time_entries (activity_id);
CREATE INDEX time_entries_spent_on ON time_entries (spent_on);
CREATE INDEX time_entries_created_at ON time_entries (created_at);

-- =====================================================================
-- Wiki
-- =====================================================================
CREATE TABLE wikis (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
  start_page TEXT NOT NULL
);
CREATE UNIQUE INDEX wikis_project_id ON wikis (project_id);

CREATE TABLE wiki_pages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  wiki_id INTEGER NOT NULL REFERENCES wikis (id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  parent_id INTEGER REFERENCES wiki_pages (id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
  protected INTEGER NOT NULL DEFAULT 0 CHECK (protected IN (0, 1)),
  -- 最新版の番号 (楽観ロックにも使う)。wiki_page_versions(page_id, version) を指す
  current_version INTEGER NOT NULL DEFAULT 0,
  created_at TEXT CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL,
  CHECK (parent_id IS NULL OR parent_id <> id)
);
CREATE UNIQUE INDEX wiki_pages_wiki_title ON wiki_pages (wiki_id, lower(title));
CREATE INDEX wiki_pages_parent_id ON wiki_pages (parent_id);

-- 全版を非圧縮で保持 (旧 wiki_contents + wiki_content_versions を統合)
CREATE TABLE wiki_page_versions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  page_id INTEGER NOT NULL REFERENCES wiki_pages (id) ON DELETE CASCADE,
  version INTEGER NOT NULL CHECK (version >= 1),
  author_id INTEGER REFERENCES principals (id) ON DELETE RESTRICT,
  text TEXT NOT NULL,
  comments TEXT,
  updated_at TEXT CHECK (updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL
);
CREATE UNIQUE INDEX wiki_page_versions_page_version ON wiki_page_versions (page_id, version);
CREATE INDEX wiki_page_versions_author_id ON wiki_page_versions (author_id);
CREATE INDEX wiki_page_versions_updated_at ON wiki_page_versions (updated_at);

CREATE TABLE wiki_redirects (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  wiki_id INTEGER NOT NULL REFERENCES wikis (id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  redirects_to TEXT NOT NULL,
  redirects_to_wiki_id INTEGER NOT NULL REFERENCES wikis (id) ON DELETE CASCADE,
  created_at TEXT CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL
);
CREATE INDEX wiki_redirects_wiki_title ON wiki_redirects (wiki_id, title);
CREATE INDEX wiki_redirects_redirects_to_wiki_id ON wiki_redirects (redirects_to_wiki_id);

-- =====================================================================
-- フォーラム
-- =====================================================================
CREATE TABLE boards (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
  parent_id INTEGER REFERENCES boards (id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  position INTEGER NOT NULL DEFAULT 1,
  topics_count INTEGER NOT NULL DEFAULT 0,
  messages_count INTEGER NOT NULL DEFAULT 0,
  last_message_id INTEGER REFERENCES messages (id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
  CHECK (parent_id IS NULL OR parent_id <> id)
);
CREATE INDEX boards_project_id ON boards (project_id, position);
CREATE INDEX boards_parent_id ON boards (parent_id);
CREATE INDEX boards_last_message_id ON boards (last_message_id);

CREATE TABLE messages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  board_id INTEGER NOT NULL REFERENCES boards (id) ON DELETE CASCADE,
  -- トピック (ルートメッセージ) の id。トピック自身は NULL
  parent_id INTEGER REFERENCES messages (id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
  subject TEXT NOT NULL,
  content TEXT,
  author_id INTEGER REFERENCES principals (id) ON DELETE RESTRICT,
  replies_count INTEGER NOT NULL DEFAULT 0,
  last_reply_id INTEGER REFERENCES messages (id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
  locked INTEGER NOT NULL DEFAULT 0 CHECK (locked IN (0, 1)),
  sticky INTEGER NOT NULL DEFAULT 0 CHECK (sticky IN (0, 1)),
  created_at TEXT CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL,
  updated_at TEXT CHECK (updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL,
  CHECK (parent_id IS NULL OR parent_id <> id)
);
CREATE INDEX messages_board_id ON messages (board_id);
CREATE INDEX messages_parent_id ON messages (parent_id);
CREATE INDEX messages_author_id ON messages (author_id);
CREATE INDEX messages_last_reply_id ON messages (last_reply_id);
CREATE INDEX messages_created_at ON messages (created_at);

-- =====================================================================
-- ニュース・文書・リアクション
-- =====================================================================
CREATE TABLE news (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  summary TEXT,
  description TEXT,
  author_id INTEGER NOT NULL REFERENCES principals (id) ON DELETE RESTRICT,
  comments_count INTEGER NOT NULL DEFAULT 0,
  created_at TEXT CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL
);
CREATE INDEX news_project_id ON news (project_id);
CREATE INDEX news_author_id ON news (author_id);
CREATE INDEX news_created_at ON news (created_at);

-- 旧 comments (commented_type='News' のみ)
CREATE TABLE news_comments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  news_id INTEGER NOT NULL REFERENCES news (id) ON DELETE CASCADE,
  author_id INTEGER NOT NULL REFERENCES principals (id) ON DELETE RESTRICT,
  content TEXT,
  created_at TEXT CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL,
  updated_at TEXT CHECK (updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL
);
CREATE INDEX news_comments_news_id ON news_comments (news_id, created_at);
CREATE INDEX news_comments_author_id ON news_comments (author_id);

CREATE TABLE documents (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
  category_id INTEGER NOT NULL REFERENCES document_categories (id) ON DELETE RESTRICT,
  title TEXT NOT NULL,
  description TEXT,
  created_at TEXT CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL
);
CREATE INDEX documents_project_id ON documents (project_id);
CREATE INDEX documents_category_id ON documents (category_id);
CREATE INDEX documents_created_at ON documents (created_at);

-- ポリモーフィック (reactable_kind + reactable_id)
CREATE TABLE reactions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  reactable_kind TEXT NOT NULL CHECK (reactable_kind IN ('issue', 'journal', 'news', 'message', 'comment')),
  reactable_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL REFERENCES user_accounts (principal_id) ON DELETE CASCADE,
  created_at TEXT CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL,
  updated_at TEXT CHECK (updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL
);
CREATE UNIQUE INDEX reactions_unique ON reactions (reactable_kind, reactable_id, user_id);
CREATE INDEX reactions_reactable ON reactions (reactable_kind, reactable_id, id);
CREATE INDEX reactions_user_id ON reactions (user_id);

-- =====================================================================
-- 添付ファイル (ポリモーフィック container_kind + container_id。NULL = 未紐付けの一時添付)
-- =====================================================================
CREATE TABLE attachments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  container_kind TEXT CHECK (container_kind IN ('issue', 'project', 'version', 'wiki_page', 'message', 'news', 'document', 'custom_value')),
  container_id INTEGER,
  filename TEXT NOT NULL,
  -- 'YYYY/MM' または NULL (古い添付はストレージ直下)
  disk_directory TEXT,
  disk_filename TEXT NOT NULL,
  filesize INTEGER NOT NULL DEFAULT 0,
  content_type TEXT,
  digest TEXT,
  digest_algo TEXT CHECK (digest_algo IN ('sha256', 'md5')),
  downloads INTEGER NOT NULL DEFAULT 0,
  author_id INTEGER NOT NULL REFERENCES principals (id) ON DELETE RESTRICT,
  description TEXT,
  created_at TEXT CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL,
  CHECK ((container_kind IS NULL) = (container_id IS NULL)),
  CHECK ((digest IS NULL) = (digest_algo IS NULL))
);
CREATE INDEX attachments_container ON attachments (container_kind, container_id);
CREATE INDEX attachments_disk_filename ON attachments (disk_filename);
CREATE INDEX attachments_digest ON attachments (digest, filesize);
CREATE INDEX attachments_author_id ON attachments (author_id);
CREATE INDEX attachments_created_at ON attachments (created_at);

-- =====================================================================
-- クエリ
-- =====================================================================
CREATE TABLE queries (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  kind TEXT NOT NULL CHECK (kind IN ('issue', 'project', 'project_admin', 'time_entry', 'user')),
  project_id INTEGER REFERENCES projects (id) ON DELETE CASCADE,
  -- NULL = システム既定クエリ (旧 user_id = 0)
  user_id INTEGER REFERENCES principals (id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  -- 0=非公開, 1=ロール限定, 2=公開
  visibility INTEGER NOT NULL DEFAULT 0 CHECK (visibility IN (0, 1, 2)),
  -- {"status_id": {"operator": "o", "values": [""]}, ...}
  filters TEXT CHECK (json_valid(filters)) NOT NULL DEFAULT '{}',
  -- NULL = 既定列
  column_names TEXT CHECK (json_valid(column_names)),
  -- [["priority", "desc"], ["id", "asc"]]
  sort_criteria TEXT CHECK (json_valid(sort_criteria)),
  group_by TEXT,
  totalable_names TEXT CHECK (json_valid(totalable_names)),
  display_type TEXT,
  -- 上記以外の options (draw_relations, draw_progress_line, draw_selected_columns, ...)
  options TEXT CHECK (json_valid(options)) NOT NULL DEFAULT '{}'
);
CREATE INDEX queries_project_id ON queries (project_id);
CREATE INDEX queries_user_id ON queries (user_id);
CREATE INDEX queries_kind_visibility ON queries (kind, visibility);

CREATE TABLE queries_roles (
  query_id INTEGER NOT NULL REFERENCES queries (id) ON DELETE CASCADE,
  role_id INTEGER NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
  PRIMARY KEY (query_id, role_id)
);
CREATE INDEX queries_roles_role_id ON queries_roles (role_id);

-- =====================================================================
-- 個人設定・通知設定
-- =====================================================================
CREATE TABLE user_preferences (
  user_id INTEGER PRIMARY KEY REFERENCES user_accounts (principal_id) ON DELETE CASCADE,
  hide_mail INTEGER NOT NULL DEFAULT 1 CHECK (hide_mail IN (0, 1)),
  -- Rails の TZ 名 (例 'Tokyo')。NULL = サーバ既定
  time_zone TEXT,
  comments_sorting TEXT NOT NULL DEFAULT 'asc' CHECK (comments_sorting IN ('asc', 'desc')),
  warn_on_leaving_unsaved INTEGER NOT NULL DEFAULT 1 CHECK (warn_on_leaving_unsaved IN (0, 1)),
  textarea_font TEXT CHECK (textarea_font IN ('monospace', 'proportional')),
  recently_used_projects INTEGER NOT NULL DEFAULT 3,
  history_default_tab TEXT,
  toolbar_language_options TEXT,
  default_issue_query_id INTEGER REFERENCES queries (id) ON DELETE SET NULL,
  default_project_query_id INTEGER REFERENCES queries (id) ON DELETE SET NULL,
  auto_watch_on TEXT CHECK (json_valid(auto_watch_on)) NOT NULL DEFAULT '[]',
  -- NULL = 既定レイアウト
  my_page_layout TEXT CHECK (json_valid(my_page_layout)),
  my_page_settings TEXT CHECK (json_valid(my_page_settings)),
  -- 未知キー・その他 (activity_scope, diff_type, gantt_zoom, gantt_months, ...)
  extra TEXT CHECK (json_valid(extra)) NOT NULL DEFAULT '{}'
);
CREATE INDEX user_preferences_default_issue_query_id ON user_preferences (default_issue_query_id);
CREATE INDEX user_preferences_default_project_query_id ON user_preferences (default_project_query_id);

CREATE TABLE user_project_bookmarks (
  user_id INTEGER NOT NULL REFERENCES user_accounts (principal_id) ON DELETE CASCADE,
  project_id INTEGER NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
  position INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, project_id)
);
CREATE INDEX user_project_bookmarks_project_id ON user_project_bookmarks (project_id);

CREATE TABLE user_recent_projects (
  user_id INTEGER NOT NULL REFERENCES user_accounts (principal_id) ON DELETE CASCADE,
  project_id INTEGER NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
  position INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, project_id)
);
CREATE INDEX user_recent_projects_project_id ON user_recent_projects (project_id);

-- 旧 users.mail_notification + user_preferences.others の通知系キーを正規化
CREATE TABLE user_notification_settings (
  user_id INTEGER PRIMARY KEY REFERENCES user_accounts (principal_id) ON DELETE CASCADE,
  -- NULL = 未設定 (Setting.default_notification_option を適用)
  mail_notification TEXT CHECK (mail_notification IN ('all', 'selected', 'only_my_events', 'only_assigned', 'only_owner', 'none')),
  no_self_notified INTEGER NOT NULL DEFAULT 1 CHECK (no_self_notified IN (0, 1)),
  notify_about_high_priority_issues INTEGER NOT NULL DEFAULT 0 CHECK (notify_about_high_priority_issues IN (0, 1)),
  channels TEXT NOT NULL DEFAULT 'email' CHECK (channels IN ('email', 'discord', 'both'))
);

-- =====================================================================
-- 設定
-- =====================================================================
CREATE TABLE settings (
  name TEXT PRIMARY KEY,
  value TEXT CHECK (json_valid(value)) NOT NULL,
  updated_at TEXT CHECK (updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL
);

-- 未知キー (プラグイン・廃止設定) の原文退避
CREATE TABLE legacy_settings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  raw_value TEXT,
  updated_at TEXT CHECK (updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z')
);
CREATE INDEX legacy_settings_name ON legacy_settings (name);

-- =====================================================================
-- リポジトリ (SCM)
-- =====================================================================
CREATE TABLE repositories (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
  scm TEXT NOT NULL CHECK (scm IN ('subversion', 'git', 'mercurial', 'cvs', 'bazaar', 'filesystem')),
  url TEXT NOT NULL,
  root_url TEXT,
  login TEXT,
  -- 暗号化列
  password TEXT,
  path_encoding TEXT,
  log_encoding TEXT,
  extra_info TEXT CHECK (json_valid(extra_info)),
  identifier TEXT,
  is_default INTEGER NOT NULL DEFAULT 0 CHECK (is_default IN (0, 1)),
  created_at TEXT CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL
);
CREATE INDEX repositories_project_id ON repositories (project_id);
CREATE UNIQUE INDEX repositories_project_identifier ON repositories (project_id, identifier) WHERE identifier IS NOT NULL;
CREATE UNIQUE INDEX repositories_project_default ON repositories (project_id) WHERE is_default = 1;

CREATE TABLE changesets (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  repository_id INTEGER NOT NULL REFERENCES repositories (id) ON DELETE CASCADE,
  revision TEXT NOT NULL,
  committer TEXT,
  committed_at TEXT CHECK (committed_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL,
  comments TEXT,
  -- コミットのローカル日付 (導出値)
  commit_date TEXT CHECK (commit_date GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'),
  scmid TEXT,
  user_id INTEGER REFERENCES principals (id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX changesets_repository_revision ON changesets (repository_id, revision);
CREATE INDEX changesets_repository_scmid ON changesets (repository_id, scmid);
CREATE INDEX changesets_committed_at ON changesets (committed_at);
CREATE INDEX changesets_user_id ON changesets (user_id);

-- 旧 changes
CREATE TABLE changeset_files (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  changeset_id INTEGER NOT NULL REFERENCES changesets (id) ON DELETE CASCADE,
  -- A/M/D/R 等の 1 文字
  action TEXT NOT NULL,
  path TEXT NOT NULL,
  from_path TEXT,
  from_revision TEXT,
  revision TEXT,
  branch TEXT
);
CREATE INDEX changeset_files_changeset_id ON changeset_files (changeset_id);

CREATE TABLE changeset_parents (
  changeset_id INTEGER NOT NULL REFERENCES changesets (id) ON DELETE CASCADE,
  parent_id INTEGER NOT NULL REFERENCES changesets (id) ON DELETE CASCADE,
  PRIMARY KEY (changeset_id, parent_id)
);
CREATE INDEX changeset_parents_parent_id ON changeset_parents (parent_id);

CREATE TABLE changesets_issues (
  changeset_id INTEGER NOT NULL REFERENCES changesets (id) ON DELETE CASCADE,
  issue_id INTEGER NOT NULL REFERENCES issues (id) ON DELETE CASCADE,
  PRIMARY KEY (changeset_id, issue_id)
);
CREATE INDEX changesets_issues_issue_id ON changesets_issues (issue_id);

-- =====================================================================
-- CSV インポート (一時データ。Redmine からは移行しない)
-- =====================================================================
CREATE TABLE imports (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  kind TEXT NOT NULL CHECK (kind IN ('issue', 'time_entry', 'user')),
  user_id INTEGER NOT NULL REFERENCES user_accounts (principal_id) ON DELETE CASCADE,
  filename TEXT,
  -- separator, wrapper, encoding, date_format, notifications, mapping, ...
  settings TEXT CHECK (json_valid(settings)) NOT NULL DEFAULT '{}',
  total_items INTEGER,
  finished INTEGER NOT NULL DEFAULT 0 CHECK (finished IN (0, 1)),
  created_at TEXT CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL,
  updated_at TEXT CHECK (updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL
);
CREATE INDEX imports_user_id ON imports (user_id);

CREATE TABLE import_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  import_id INTEGER NOT NULL REFERENCES imports (id) ON DELETE CASCADE,
  position INTEGER NOT NULL,
  obj_id INTEGER,
  message TEXT,
  unique_id TEXT
);
CREATE INDEX import_items_import_unique_id ON import_items (import_id, unique_id);
CREATE INDEX import_items_import_position ON import_items (import_id, position);

-- =====================================================================
-- OAuth2 プロバイダ (Doorkeeper 互換)
-- =====================================================================
CREATE TABLE oauth_applications (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  uid TEXT NOT NULL,
  -- BCrypt ハッシュ
  secret TEXT NOT NULL,
  redirect_uri TEXT NOT NULL,
  -- スペース区切り
  scopes TEXT NOT NULL DEFAULT '',
  confidential INTEGER NOT NULL DEFAULT 1 CHECK (confidential IN (0, 1)),
  created_at TEXT CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL,
  updated_at TEXT CHECK (updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL
);
CREATE UNIQUE INDEX oauth_applications_uid ON oauth_applications (uid);

CREATE TABLE oauth_access_grants (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  resource_owner_id INTEGER NOT NULL REFERENCES user_accounts (principal_id) ON DELETE CASCADE,
  application_id INTEGER NOT NULL REFERENCES oauth_applications (id) ON DELETE CASCADE,
  -- SHA-256 hex
  token TEXT NOT NULL,
  expires_in INTEGER NOT NULL,
  redirect_uri TEXT NOT NULL,
  created_at TEXT CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL,
  revoked_at TEXT CHECK (revoked_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z'),
  scopes TEXT,
  code_challenge TEXT,
  code_challenge_method TEXT
);
CREATE UNIQUE INDEX oauth_access_grants_token ON oauth_access_grants (token);
CREATE INDEX oauth_access_grants_application_id ON oauth_access_grants (application_id);
CREATE INDEX oauth_access_grants_resource_owner_id ON oauth_access_grants (resource_owner_id);

CREATE TABLE oauth_access_tokens (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  resource_owner_id INTEGER REFERENCES user_accounts (principal_id) ON DELETE CASCADE,
  application_id INTEGER REFERENCES oauth_applications (id) ON DELETE CASCADE,
  -- SHA-256 hex
  token TEXT NOT NULL,
  refresh_token TEXT,
  expires_in INTEGER,
  revoked_at TEXT CHECK (revoked_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z'),
  created_at TEXT CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL,
  scopes TEXT,
  previous_refresh_token TEXT NOT NULL DEFAULT ''
);
CREATE UNIQUE INDEX oauth_access_tokens_token ON oauth_access_tokens (token);
CREATE UNIQUE INDEX oauth_access_tokens_refresh_token ON oauth_access_tokens (refresh_token);
CREATE INDEX oauth_access_tokens_resource_owner_id ON oauth_access_tokens (resource_owner_id);
CREATE INDEX oauth_access_tokens_application_id ON oauth_access_tokens (application_id);

-- =====================================================================
-- 基盤: ジョブキュー・通知
-- =====================================================================
CREATE TABLE jobs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  queue TEXT NOT NULL DEFAULT 'default',
  -- ジョブ種別 (例 'notify.email', 'notify.discord', 'attachment.thumbnail')
  kind TEXT NOT NULL,
  payload TEXT CHECK (json_valid(payload)) NOT NULL DEFAULT '{}',
  state TEXT NOT NULL DEFAULT 'pending' CHECK (state IN ('pending', 'running', 'succeeded', 'failed')),
  priority INTEGER NOT NULL DEFAULT 0,
  run_at TEXT CHECK (run_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  max_attempts INTEGER NOT NULL DEFAULT 25,
  last_error TEXT,
  locked_by TEXT,
  locked_at TEXT CHECK (locked_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z'),
  -- 重複投入防止キー (pending/running の間だけ一意)
  unique_key TEXT,
  created_at TEXT CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL,
  updated_at TEXT CHECK (updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL,
  finished_at TEXT CHECK (finished_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z')
);
CREATE INDEX jobs_poll ON jobs (state, queue, run_at, priority);
CREATE INDEX jobs_finished_at ON jobs (finished_at);
CREATE UNIQUE INDEX jobs_unique_key ON jobs (unique_key) WHERE unique_key IS NOT NULL AND state IN ('pending', 'running');

CREATE TABLE notification_deliveries (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  job_id INTEGER REFERENCES jobs (id) ON DELETE SET NULL,
  user_id INTEGER REFERENCES user_accounts (principal_id) ON DELETE SET NULL,
  channel TEXT NOT NULL CHECK (channel IN ('email', 'discord')),
  -- issue_added, issue_updated, news_added, ... / account_activation 等
  event TEXT NOT NULL,
  object_kind TEXT,
  object_id INTEGER,
  -- メールアドレス / Discord ユーザー ID
  recipient TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'failed', 'skipped')),
  attempts INTEGER NOT NULL DEFAULT 0,
  error TEXT,
  created_at TEXT CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL,
  sent_at TEXT CHECK (sent_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z')
);
CREATE INDEX notification_deliveries_created_at ON notification_deliveries (created_at);
CREATE INDEX notification_deliveries_user_id ON notification_deliveries (user_id, created_at);
CREATE INDEX notification_deliveries_job_id ON notification_deliveries (job_id);
CREATE INDEX notification_deliveries_object ON notification_deliveries (object_kind, object_id);

CREATE TABLE discord_dm_channels (
  user_id INTEGER PRIMARY KEY REFERENCES user_accounts (principal_id) ON DELETE CASCADE,
  discord_user_id TEXT NOT NULL,
  channel_id TEXT NOT NULL,
  -- 恒久エラーの連続回数 (閾値超過でメールへフォールバック)
  consecutive_failures INTEGER NOT NULL DEFAULT 0,
  last_error TEXT,
  created_at TEXT CHECK (created_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL,
  updated_at TEXT CHECK (updated_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9]Z') NOT NULL
);

-- +goose Down
PRAGMA defer_foreign_keys = ON;
DROP TABLE IF EXISTS discord_dm_channels;
DROP TABLE IF EXISTS notification_deliveries;
DROP TABLE IF EXISTS jobs;
DROP TABLE IF EXISTS oauth_access_tokens;
DROP TABLE IF EXISTS oauth_access_grants;
DROP TABLE IF EXISTS oauth_applications;
DROP TABLE IF EXISTS import_items;
DROP TABLE IF EXISTS imports;
DROP TABLE IF EXISTS changesets_issues;
DROP TABLE IF EXISTS changeset_parents;
DROP TABLE IF EXISTS changeset_files;
DROP TABLE IF EXISTS changesets;
DROP TABLE IF EXISTS repositories;
DROP TABLE IF EXISTS legacy_settings;
DROP TABLE IF EXISTS settings;
DROP TABLE IF EXISTS user_notification_settings;
DROP TABLE IF EXISTS user_recent_projects;
DROP TABLE IF EXISTS user_project_bookmarks;
DROP TABLE IF EXISTS user_preferences;
DROP TABLE IF EXISTS queries_roles;
DROP TABLE IF EXISTS queries;
DROP TABLE IF EXISTS attachments;
DROP TABLE IF EXISTS reactions;
DROP TABLE IF EXISTS documents;
DROP TABLE IF EXISTS news_comments;
DROP TABLE IF EXISTS news;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS boards;
DROP TABLE IF EXISTS wiki_redirects;
DROP TABLE IF EXISTS wiki_page_versions;
DROP TABLE IF EXISTS wiki_pages;
DROP TABLE IF EXISTS wikis;
DROP TABLE IF EXISTS time_entries;
DROP TABLE IF EXISTS watchers;
DROP TABLE IF EXISTS issue_journal_details;
DROP TABLE IF EXISTS issue_journals;
DROP TABLE IF EXISTS issue_relations;
DROP TABLE IF EXISTS issues;
DROP TABLE IF EXISTS issue_categories;
DROP TABLE IF EXISTS versions;
DROP TABLE IF EXISTS workflow_field_rules;
DROP TABLE IF EXISTS workflow_transitions;
DROP TABLE IF EXISTS custom_values;
DROP TABLE IF EXISTS custom_fields_trackers;
DROP TABLE IF EXISTS custom_fields_roles;
DROP TABLE IF EXISTS custom_fields_projects;
DROP TABLE IF EXISTS custom_field_enumerations;
DROP TABLE IF EXISTS custom_fields;
DROP TABLE IF EXISTS user_notified_projects;
DROP TABLE IF EXISTS member_roles;
DROP TABLE IF EXISTS members;
DROP TABLE IF EXISTS roles_managed_roles;
DROP TABLE IF EXISTS role_permission_trackers;
DROP TABLE IF EXISTS role_permissions;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS time_entry_activities;
DROP TABLE IF EXISTS document_categories;
DROP TABLE IF EXISTS issue_priorities;
DROP TABLE IF EXISTS project_trackers;
DROP TABLE IF EXISTS project_modules;
DROP TABLE IF EXISTS project_closure;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS trackers;
DROP TABLE IF EXISTS issue_statuses;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS twofa_backup_codes;
DROP TABLE IF EXISTS tokens;
DROP TABLE IF EXISTS user_identities;
DROP TABLE IF EXISTS auth_source_group_mappings;
DROP TABLE IF EXISTS group_users;
DROP TABLE IF EXISTS email_addresses;
DROP TABLE IF EXISTS user_accounts;
DROP TABLE IF EXISTS principals;
DROP TABLE IF EXISTS auth_sources;
