# frozen_string_literal: true

# Rouge のレキサー一覧（タグ・別名・ファイル名パターン）から
# internal/textformat/highlight/rouge_lexers_gen.go を生成する。
#
#   cd /path/to/redmine
#   bin/rails runner /path/to/buropher/tools/gen-rouge-lexers.rb \
#     /path/to/buropher/internal/textformat/highlight/rouge_lexers_gen.go

out_path = ARGV[0] or abort 'usage: gen-rouge-lexers.rb OUT.go'

lexers = Rouge::Lexer.all.sort_by(&:tag)
q = ->(s) { s.to_s.inspect }

src = +"// SPDX-License-Identifier: GPL-2.0-or-later AND MIT\n// Copyright (C) 2026 mikuta0407 and Buropher contributors\n// Portions ported from Rouge (https://github.com/rouge-ruby/rouge),\n// Copyright (c) 2012 Jeanine Adkisson and contributors, MIT License.\n\n// Code generated by tools/gen-rouge-lexers.rb from Rouge #{Rouge.version}. DO NOT EDIT.\n\n"
src << "package highlight\n\n"
src << "// rougeLexer は Rouge のレキサー定義（タグ、別名、ファイル名パターン）。\n"
src << "type rougeLexer struct {\n\tTag       string\n\tAliases   []string\n\tFilenames []string\n}\n\n"
src << "var rougeLexers = []rougeLexer{\n"
lexers.each do |l|
  src << "\t{Tag: #{q[l.tag]}, Aliases: []string{#{l.aliases.map(&q).join(', ')}}, Filenames: []string{#{(l.filenames || []).map(&q).join(', ')}}},\n"
end
src << "}\n"
File.write(out_path, src)
STDERR.puts "wrote #{lexers.size} lexers"
